In [38]:
import tensorflow as tf
import numpy as np
from PIL import Image

In [49]:
image_SIZE = 224 # image size
def load_image(path):
    # load image
    img = Image.open(path)
    width, height = img.size
    if(width > image_SIZE and height > image_SIZE):
        tmp_max = max(width, height)
        tmp_min = min(width, height)
        x = int((tmp_max - width)/2)
        y = int((tmp_max - height)/2)
        resized_img = img.crop((x, y, tmp_min+x, tmp_min+y))
    resized_img = img.resize((image_SIZE, image_SIZE))
    return resized_img

def cov_layer(image,kernelmap_number):
    #初始化kernelmap
    kernel_map = tf.Variable(tf.random_normal
                ([kernelmap_number,3,3,1]))
    con_ans = tf.nn.conv2d(image,kernel_map,strides=[1, 1, 1, 1],padding='SAME')
    return con_ans
    
    
#with tf.device("/gpu:0"): 

image = load_image("/home/linux/Desktop/test1/11.jpg")
red, green, blue = image.split()
image_red = np.asarray(red)
image_green = np.asarray(green)
image_blue = np.asarray(blue)

_inputRGB = tf.placeholder(tf.float32,
                          [None,
                          224,224,3])




[[221 221 222 ... 197 198 199]
 [221 222 222 ... 198 197 197]
 [224 224 225 ... 198 197 195]
 ...
 [203 203 203 ... 230 228 225]
 [205 205 205 ... 226 225 223]
 [203 203 206 ... 218 219 224]] 0
[[222 222 223 ... 200 201 202]
 [222 223 223 ... 201 200 200]
 [225 225 226 ... 201 200 198]
 ...
 [185 185 185 ... 218 216 213]
 [187 187 187 ... 214 213 211]
 [185 185 188 ... 202 205 208]] 1
[[216 216 217 ... 205 206 207]
 [216 217 217 ... 206 205 205]
 [219 219 220 ... 206 205 203]
 ...
 [181 181 181 ... 218 216 213]
 [183 183 183 ... 214 213 211]
 [183 183 186 ... 202 202 208]]
